# Using this file requires the VS Code REST Client extension: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

// Post Request to add new User
POST http://localhost:3000/api/clients
Content-Type: application/json

{
    "firstname": "Jon",
    "lastname": "doe",
    "email": "email@gmailnetcom.net",
    "password": "mypassword",
    "street": "123 Maple Street",
    "city": "Glendale",
    "state": "California",
    "bundle": "Green Thumb Bundle",
    "pic": "myhome.jpg"
}

